import { useMemo, useState } from "react";
import { PageHeader } from "../../../../components/common/PageHeader";
import { InputPanel } from "../../../../components/common/InputPanel";
import { WarningBadge } from "../../../../components/common/WarningBadge";
import { aesInvSBox, aesSBox } from "./aesTables";
export default function AESSBoxExplorerPage() {
  const [byte, setByte] = useState("53");
  const [inverse, setInverse] = useState(false);
  const table = inverse ? aesInvSBox : aesSBox;
  const clean = byte.replace(/[^0-9a-f]/gi, "").padStart(2, "0").slice(0,2);
  const row = parseInt(clean[0], 16), col = parseInt(clean[1], 16), out = table[row * 16 + col];
  const cells = useMemo(() => table.map((v, i) => v.toString(16).padStart(2, "0")), [table]);
  return <div className="space-y-6"><PageHeader title="AES S-Box Explorer" category="Block Ciphers" status="Educational">Use the real AES S-box and inverse S-box to inspect byte substitution by row and column.</PageHeader><InputPanel title="Select a byte"><div className="grid gap-3 md:grid-cols-3"><label className="label">Hex byte<input className="field mt-1 font-mono" value={byte} onChange={(e)=>setByte(e.target.value)} /></label><label className="label">Table<select className="field mt-1" value={inverse ? "inverse" : "forward"} onChange={(e)=>setInverse(e.target.value==="inverse")}><option value="forward">AES S-box</option><option value="inverse">AES inverse S-box</option></select></label><div className="rounded-md bg-cyan-50 p-3"><div className="text-xs uppercase text-cyan-700">Selected output</div><div className="font-mono text-2xl font-bold">{out.toString(16).padStart(2,"0")}</div></div></div></InputPanel><section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Real 16x16 AES table</h2><div className="grid grid-cols-16 gap-1">{cells.map((cell, index)=><div key={index} className={`rounded px-1 py-2 text-center font-mono text-xs ${index === row * 16 + col ? "bg-cyan-600 text-white" : Math.floor(index/16)===row || index%16===col ? "bg-cyan-50 text-cyan-900" : "bg-slate-100"}`}>{cell}</div>)}</div></section><section className="grid gap-6 xl:grid-cols-2"><div className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Nibble lookup</h2><p className="mt-2 text-sm text-slate-600">The high nibble <span className="font-mono">{clean[0]}</span> chooses row {row}; the low nibble <span className="font-mono">{clean[1]}</span> chooses column {col}. The substitution changes <span className="font-mono">{clean}</span> into <span className="font-mono">{out.toString(16).padStart(2,"0")}</span>.</p></div><div className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">GF(2^8) construction</h2><p className="mt-2 text-sm text-slate-600">AES computes a multiplicative inverse in GF(2^8), treating 00 specially, then applies an affine transform. This gives nonlinear confusion without relying on secret S-box values.</p><WarningBadge>The table is public and fixed; never replace it with made-up values.</WarningBadge></div></section></div>;
}

